apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp
spec:
  matchLabels:
    app: frontend-deployment
  metadata:
    labels:
      app: frontend-deployment
  spec:
    containers:
    - name: apple
      ports:
      - containerPort: "2345"
        name: http
