apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp
spec:
  selector:
    matchLabels:
      app: frontend-deployment
  template:
    metadata:
      labels:
        app: frontend-deployment
    spec:
      containers:
      - image: nginx:1.14.2
        name: orange
        ports:
        - containerPort: 3449
          name: http
      - image: alpine
        name: app
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
