apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp
spec:
  selector:
    matchLabels:
      app: frontend-deployment
  template:
    metadata:
      labels:
        app: frontend-deployment
    spec:
      containers:
      - command:
        - tail
        - -f
        - /dev/null
        image: nginx:1.14.2
        name: apple
        ports:
        - containerPort: 3448
          name: http
      - image: alpine
        name: app
        ports:
        - containerPort: 80
          name: http
