apiVersion: apps/v1
kind: Deployment
metadata:
  name: saitejaapp
spec:
  selector:
    matchLabels:
      app: frontend-deployment
  template:
    metadata:
      labels:
        app: frontend-deployment
    spec:
      containers:
      - image: nginx:1.14.2
        name: saiteja
        ports:
        - containerPort: 9999
          name: http
      - command:
        - tail
        - -f
        - /dev/null
        image: alpine
        name: app
        ports:
        - containerPort: 80
          name: http
